Replace PRIVATE_REPO_NAME variable with CUSTOM_PART_FOLDER_NAME, expand regex to avoid removing completeness_report folder

diff --git a/scripts/Makefile b/scripts/Makefile
--- a/scripts/Makefile
+++ b/scripts/Makefile
@@ -4,14 +4,13 @@
 # Add here export for every varible from configuration file that you are going to use in targets
 export PGDATABASE = $(shell sed -n -e '/^PGDATABASE/p' ${configuration_file} | cut -d "=" -f 2)
 export PGUSER = $(shell sed -n -e '/^PGUSER/p' ${configuration_file} | cut -d "=" -f 2)
-export GENERAL_FOLDER = $(shell sed -n -e '/^GENERAL_FOLDER/p' ${configuration_file} | cut -d "=" -f 2)
 export SLACK_CHANNEL = $(shell sed -n -e '/^SLACK_CHANNEL/p' ${configuration_file} | cut -d "=" -f 2)
 export SLACK_BOT_NAME = $(shell sed -n -e '/^SLACK_BOT_NAME/p' ${configuration_file} | cut -d "=" -f 2)
 export SLACK_BOT_EMOJI = $(shell sed -n -e '/^SLACK_BOT_EMOJI/p' ${configuration_file} | cut -d "=" -f 2)
 export SLACK_BOT_KEY = $(shell sed -n -e '/^SLACK_BOT_KEY/p' ${configuration_file} | cut -d "=" -f 2)
 
 export GEOCINT_WORK_DIRECTORY = $(shell sed -n -e '/^GEOCINT_WORK_DIRECTORY/p' ${configuration_file} | cut -d "=" -f 2)
-export PRIVATE_REPO_NAME = $(shell sed -n -e '/^PRIVATE_REPO_NAME/p' ${configuration_file} | cut -d "=" -f 2)
+export CUSTOM_PART_FOLDER_NAME = $(shell sed -n -e '/^CUSTOM_PART_FOLDER_NAME/p' ${configuration_file} | cut -d "=" -f 2)
 
 
 # -------------------- PREPARATIONS BLOCK -----------------------------------
@@ -19,40 +18,40 @@ export PRIVATE_REPO_NAME = $(shell sed -n -e '/^PRIVATE_REPO_NAME/p' ${configura
 ${GEOCINT_WORK_DIRECTORY}: ## create working directory
 	mkdir -p $@
 
-${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}: | ${GEOCINT_WORK_DIRECTORY} ## create general_folder directory
+${GEOCINT_WORK_DIRECTORY}/geocint: | ${GEOCINT_WORK_DIRECTORY} ## create general_folder directory
 	mkdir -p $@
 
-${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation: | ${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER} ## create installation folder to store installation process marks
+${GEOCINT_WORK_DIRECTORY}/geocint/installation: | ${GEOCINT_WORK_DIRECTORY}/geocint ## create installation folder to store installation process marks
 	mkdir -p $@
 
-${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/add_congig_file_path_to_bashrc: | ${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation ## write export variable to bashrc file
+${GEOCINT_WORK_DIRECTORY}/geocint/installation/add_congig_file_path_to_bashrc: | ${GEOCINT_WORK_DIRECTORY}/geocint/installation ## write export variable to bashrc file
 	sudo echo 'export GEOCINT_WORK_DIRECTORY=${GEOCINT_WORK_DIRECTORY}' >> ${HOME}/.bashrc
 	touch $@
 
-${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/preparation_block_finished: ${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/add_congig_file_path_to_bashrc ## send message that preparation step finished successfully
+${GEOCINT_WORK_DIRECTORY}/geocint/installation/preparation_block_finished: ${GEOCINT_WORK_DIRECTORY}/geocint/installation/add_congig_file_path_to_bashrc ## send message that preparation step finished successfully
 	echo "Preparation step finished successfully"
 	touch $@
 
 
 # -------------------- DEPENDENCIES INSTALLATIONS BLOCK ----------------------
 
-${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/runner_installer: ${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/preparation_block_finished ## install dependencies of runner part 
+${GEOCINT_WORK_DIRECTORY}/geocint/installation/runner_installer: ${GEOCINT_WORK_DIRECTORY}/geocint/installation/preparation_block_finished ## install dependencies of runner part 
 	bash ${GEOCINT_WORK_DIRECTORY}/geocint-runner/runner-install.sh || echo 'runner-install.sh returned an error, check logs for more infornation'
 	touch $@
 
-${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/openstreetmap_installer: ${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/runner_installer ## install dependencies of openstreetmap part
+${GEOCINT_WORK_DIRECTORY}/geocint/installation/openstreetmap_installer: ${GEOCINT_WORK_DIRECTORY}/geocint/installation/runner_installer ## install dependencies of openstreetmap part
 	bash ${GEOCINT_WORK_DIRECTORY}/geocint-openstreetmap/openstreetmap-install.sh || echo 'openstreetmap-install.sh returned an error, check logs for more infornation'
 	touch $@
 
-${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/h3_pg_installation: ${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/openstreetmap_installer ## install h3_pg
+${GEOCINT_WORK_DIRECTORY}/geocint/installation/h3_pg_installation: ${GEOCINT_WORK_DIRECTORY}/geocint/installation/openstreetmap_installer ## install h3_pg
 	sudo pgxn install h3
 	touch $@
 
-${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/private_installer: ${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/h3_pg_installation ## install dependencies of openstreetmap part
-	bash ${GEOCINT_WORK_DIRECTORY}/${PRIVATE_REPO_NAME}/install.sh || echo 'install.sh returned an error, check logs for more infornation'
+${GEOCINT_WORK_DIRECTORY}/geocint/installation/private_installer: ${GEOCINT_WORK_DIRECTORY}/geocint/installation/h3_pg_installation ## install dependencies of openstreetmap part
+	bash ${GEOCINT_WORK_DIRECTORY}/${CUSTOM_PART_FOLDER_NAME}/install.sh || echo 'install.sh returned an error, check logs for more infornation'
 	touch $@
 
-${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/set_modes: ${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/private_installer ## create public_html folder and set access
+${GEOCINT_WORK_DIRECTORY}/geocint/installation/set_modes: ${GEOCINT_WORK_DIRECTORY}/geocint/installation/private_installer ## create public_html folder and set access
 	sudo usermod -aG adm ${USER}
 	sudo usermod -aG ${USER} www-data
 	sudo mkdir -p ${GEOCINT_WORK_DIRECTORY}/public_html
@@ -61,22 +60,22 @@ ${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/set_modes: ${GEOCINT_WO
 	sudo echo 'export PATH=$$PATH:/usr/local/pgsql/bin' >> ${HOME}/.bashrc
 	touch $@
 
-${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/installation_block_finished: ${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/set_modes ## send message that installation step finished successfully
+${GEOCINT_WORK_DIRECTORY}/geocint/installation/installation_block_finished: ${GEOCINT_WORK_DIRECTORY}/geocint/installation/set_modes ## send message that installation step finished successfully
 	echo "Installation step finished successfully"
 	touch $@
 
 
 # ------------------------ DB configuration block ----------------------------
 
-${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/create_user: ${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/installation_block_finished ## create postgresql user
+${GEOCINT_WORK_DIRECTORY}/geocint/installation/create_user: ${GEOCINT_WORK_DIRECTORY}/geocint/installation/installation_block_finished ## create postgresql user
 	sudo -u postgres psql -c "CREATE ROLE ${PGUSER} WITH SUPERUSER LOGIN ENCRYPTED PASSWORD '${PGUSER}pass';"
 	touch $@
 	
-${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/create_database: ${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/create_user ## create postgresql db
+${GEOCINT_WORK_DIRECTORY}/geocint/installation/create_database: ${GEOCINT_WORK_DIRECTORY}/geocint/installation/create_user ## create postgresql db
 	sudo -u postgres psql -c "CREATE DATABASE ${PGDATABASE} WITH OWNER ${PGUSER};"
 	touch $@
 	
-${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/create_extensions: ${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/create_database ## create postgresql extensions
+${GEOCINT_WORK_DIRECTORY}/geocint/installation/create_extensions: ${GEOCINT_WORK_DIRECTORY}/geocint/installation/create_database ## create postgresql extensions
 	psql -c "CREATE EXTENSION postgis;"
 	psql -c "CREATE EXTENSION postgis_raster;"
 	psql -c "CREATE EXTENSION postgis_sfcgal;"
@@ -85,12 +84,12 @@ ${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/create_extensions: ${GE
 	psql -c "CREATE EXTENSION h3_postgis;"
 	touch $@
 
-${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/database_block_finished: ${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/create_extensions ## send message that database initialisation step finished successfully
+${GEOCINT_WORK_DIRECTORY}/geocint/installation/database_block_finished: ${GEOCINT_WORK_DIRECTORY}/geocint/installation/create_extensions ## send message that database initialisation step finished successfully
 	echo "Database initialisation step finished successfully"
 	touch $@
 
 
 # ------------------------ MANAGE BLOCK ---------------------------------------
 
-install: ${GEOCINT_WORK_DIRECTORY}/${GENERAL_FOLDER}/installation/database_block_finished ## Target to run Geocint pipeline installation
+install: ${GEOCINT_WORK_DIRECTORY}/geocint/installation/database_block_finished ## Target to run Geocint pipeline installation
 	echo "Geocint pipeline successfully installed"
